### ISSUE TITLE
Tracking issue: problems loading the init file

### ISSUE THREAD

**Issue by SnirkImmington** [Immington-Industries/way-cooler#118]
Pains with the init file is one of the biggest issues new users run into. If `init.lua` is missing, or invalid in some way, way-cooler will crash somewhat unhelpfully. I have many ideas about making the process smother and robust that I had put off, that need to be implemented.

**Included default init file**
- [ ] Compile `config/init.lua` into `way-cooler` to use as the default init file.
- [ ] Add `--default-init` flag to force using this "internal" init file (i.e. for developers, and as a first suggestion in bug reports...)
- [ ] Add `--init-file=<path>` arg as an alternative to setting`$WAY_COOLER_INIT_FILE` (if both are specified, only look at the command line)
- [ ] Add `export-init <path>` to save this init file to disk (and consider doing it during first run/etc). Executing `way-cooler export-init <path>` should not run the wm, and should be used in install scripts.
- [ ] Also `--print-init`? To print directly to stdout? `way-cooler export-init [-o <path>]`?
- [ ] Add a comment programmatically at the beginning of the default init file saying which way-cooler version it was generated in. This way if later commands are added and the user still has a default init file from an old version, they can know to regenerate it.
* In the future, "flavors" of `way-cooler` may be provided with different default init files.

**Selecting the init file**
- [ ] The Lua thread should print directly to `stdout` if it cannot find an init file instead of logs (and use the default one anyway). 
- [ ] The Lua thread should print specific explanations if it looks for an init file from environment variables (i.e. `XDG_CONFIG_DIR`) but cannot find `init.lua`.
- [ ] way-cooler will print a helpful message to stdout saying how to save and modify the init file.
* In the future, it should be easy to ask way-cooler to auto-reload init file changes.

**Running initialization**
- [ ] Useful error messages should be printed directly to stderr ("command <name> cannot be found", "<foo> is not a recognized key", along with the accompanying line of the init file.
- [ ] If the init file fails, the Lua keybindings shall be cleared, Lua state re-initialized, and the default init file re-run.
- [ ] We should attempt to print other error messages in a more helpful way (the string escaping is pretty bad; there might be a `format!` flag to disable it?)
* In the future, way-cooler should be able to safely rollback some changes made during initialization, and to more thoroughly test whether an init file is valid.

**Comment by Timidger** [comment]
>Add --default-init flag to force using this "internal" init file (i.e. for developers, and as a first suggestion in bug reports...)

So I'm confused, are we keeping the init file in the binary and then defaulting to using that, or are we providing a mechanism to generate and then use a configuration file if none are found? The latter seems much less error prone, because there will always be some file behind the configuration file. Having a dual setup would be convenient for development, but I think it could potentially cause problems in production by being unnecessarily complicated. If we _only_ use this inner configuration when we supply the `--default-init` flag then I have no problem with that, as that is much more explicit.

I like the configuration file generation idea, not to bike shed too much but shouldn't the command be a flag to Way Cooler, as opposed to this weird "sub command" right now (e.g `--export-init=/etc/way-cooler/`). We don't have any other sub commands, so it would just seem out of place. Also, `--default-init` sounds a *little* off, perhaps a better command would be `--debug-init`, to specify that this is something primarily used for debugging? I don't think it'd be used for much else (as everything else should be generated with the previously mentioned flag and placed somewhere on the user's system).

`--print-init` is a little unnecessary, we should probably either just have one that writes it to a file or else have the command print it out to stdout and then we can redirect into a file.

Not sure if you're aware as well, but currently the configuration file doesn't handle the `XDG_CONFIG_DIR` var properly, it doesn't check that `$XDG_CONFIG_DIR/way-cooler` HAS the config file, it checks if that path IS the config file.

Another thing that needs to be considered is what to do if a user loads up the WM using the default config located in a sane place (i.e `/etc/way-cooler/init.lua`), then copies that file into the home directory, modifies it, and then reloads the config. Should we reload with the original, or try to get a different one based off the previously discussed choosing algorithm. Are there any conflicts with that? E.g is it *always* correct to grab the best one we can find?

**Comment by SnirkImmington** [comment]
> So I'm confused, are we keeping the init file in the binary and then defaulting to using that, or are we providing a mechanism to generate and then use a configuration file if none are found?

We should have an init file "in the binary" and default to using that. So there should be 1) user-supplied init file 2) compiled-in default. The default file should be written into a config folder and modified by the user - this should be done by either the package manager, or the user (via the config-write command).

We should **not** keep loading init files at all the paths [listed bellow] if one doesn't work (i.e. if one is defined at each point, run all of them) - that's probably a terrible idea.

Your points on not having a subcommand (`way-cooler export-init`) for saving the compiled-in default are fair - let me know if you have better naming ideas. 

> Having a dual setup would be convenient for development, but I think it could potentially cause problems in production by being unnecessarily complicated.

What I meant by `--default-init` being for developers and bug reports:

1. When we develop, we need to make sure the default config of the new way-cooler works, and test any new additions it adds (and imagine when we are running it nested inside of our main way-cooler setups), and it was kind of a joke about how many times I've added a new command, been confused why it didn't work, and remember `cargo run` used an init file from an older version, etc.
2. The _first_ thing developers of any program with a Turing-complete configuration do when receiving a bug report is usually to ask users to re-run with the default config (i.e. spacemacs, i3, awesome, you name it). Making that a simple command line flag makes our job a lot easier.

You're right that those would be the _main_ usecases, but there are other uses for it (i.e. user-configured init file is broken, user doesn't want to wait for way-cooler to cycle out the default one). But I think a name like `--debug-init` sounds like it would use some kind of "debugging" initialization - like printing more logs, or something. I'd rather the command specify what it was doing than guess when it would be used. We could also use `--init ['default'|<path>]` or something.

> Should we reload with the original, or try to get a different one based off the previously discussed choosing algorithm

The choosing isn't really an _algorithm_, it's just an order (yes, I know an algorithm is a series of steps). Basically we have:

1. User has used program arg `--init-file=` or `--default-init` when running way-cooler [we _need_ to use that right away]
2. User has specified `$WAY_COOLER_INIT` environment arg [they certainly set something up (and at this point it's kinda for backwards compatability), we should use it]
3. User has init file in `$XDG_CONFIG_DIR` [the user's wants are probably more specific than the system's [`/etc`], and they used this fancy env var]
4. User has init file in `~/.config` [again, user's wants are more important than the system's]
5. User has init file in `/etc` [very basic directory to store places]

The numbers here are just my best guess at "what is most important" to guess first - roughly how far out of their way did the user go to specify something? If they had an existing configuration, but wanted to _override_ it (i.e. for debugging, bug reports, change of style, updating, older backups to revert to), what should we use? Now that we can build-in the default, we can assume there's _usually_ only one other init file. 

> then copies that file into the home directory, modifies it, and then reloads the config

As you can see, the home directory paths are higher up, so it would use that one. The reasoning behind this is maybe a multi-user system would have something at `/etc` but users would want configuration in their home folders. As I mentioned above, we also don't try to load more than one file before defaulting.

I think we should stick with that algorithm every time we look for the init file, to be consistent. Consistency is probably more important than cleverness there. The home directory configs should _always_ shadow `/etc`.

**Comment by Timidger** [comment]
> What I meant by --default-init being for developers and bug reports: ...

Right, I agree with all those points, what I meant to say (didn't make my self clear) was that I was concerned it would be confusing if for example someone gets Way Cooler by compiling it manually, but then doesn't put a configuration file any where. Now, the "correct" thing to do would probably be to write a configuration file after one couldn't be found (and if the `--default-init` flag is not provided) because otherwise they could keep using it without specifying a file for it, but so long as we are clear in logging that we are using the internal configuration file (and that there's some way for us to refer to it, even if it only exists in the git history) then it should be fine...

> The choosing isn't really an algorithm, it's just an order (yes, I know an algorithm is a series of steps)...

Yeah didn't know what word to use here, so I went with the most politically correct one.

> As you can see, the home directory paths are higher up...

Right, and that's the order I assumed would make the most sense as well when doing a simple in-place restart. But in that cause you'd have to be sure that any of the old state from the old config file is wiped, because otherwise the soft restart and a hard restart would have different results...Right now that might be the case, but it depends what's built into the init file and how the restart mechanism is handled.

**Comment by SnirkImmington** [comment]
> You mean 0.3.4
I'll do that bugfix for 0.0.3, will remove from the list of things for 0.3.4.

**Comment by Timidger** [comment]
Damn, I edited that, saw what you meant, then thought I deleted it again. ¯\_(ツ)_/¯

**Comment by SnirkImmington** [comment]
I will split this issue up as it is pointlessly large, and tracking issues can be represented with GitHub Projects.

**Comment by SnirkImmington** [comment]
I've split this issue into the three listed above. Apologies to @Timidger if I missed some of your comments in the new issues. Discussion should be moved to the relevant issues.
